#!/usr/bin/env bash
set -e

was_sourced="${BASH_SOURCE[0]}"
[ "${was_sourced}" = "$0" ] && was_sourced=

key_encoder_string="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"

#echo "$bname_bucket"
#echo "Files: $bname_files"
#for bname_cursor in $bname_files; do
#  echo "f: $bname_cursor"
#done

function bname_key() {
  #date -d "${BNAME_DATE}" '+%y%m%d%U'
  year=$(bname_key_year)
  month=$(bname_key_month)
  week=$(bname_key_week)
  day=$(bname_key_day)
  # shellcheck disable=SC2059
  printf "\x$(printf %x "$year")\x$(printf %x "$month")$day\x$(printf %x "$week")"
}

function bname_key_year() {
  local key_index=$(( $(date -d "${BNAME_DATE}" '+%y') - 20 ))
  echo "${key_encoder_string:$key_index:1}"
}

function bname_key_month() {
  local key_index=$(( $(date -d "${BNAME_DATE}" '+%m') - 0 ))
  echo "${key_encoder_string:$key_index:1}"
}

function bname_key_week() {
  date -d "${BNAME_DATE}" '+%U'
}

function bname_key_day() {
  local key_index=$(( $(date -d "${BNAME_DATE}" '+%d') - 0 ))
  echo "${key_encoder_string:$key_index:1}"
}

function bname_prefix() {
  date -d "${BNAME_DATE}" '+%Y%m%d%H%M'
}

function bname_date() {
  date -d "${BNAME_DATE}" '+%y-%m-%d (%U) %H:%M'
}

function bname_snapshot() {
  local bname_key=$(bname_key)
  local bname_prefix=$(bname_prefix)
  case $1 in
    year)
      echo "${bname_prefix}_A${bname_key}_${2}"
      ;;
    month)
      echo "${bname_prefix}_B${bname_key}_${2}"
      ;;
    week)
      echo "${bname_prefix}_C${bname_key}_${2}"
      ;;
    day)
      echo "${bname_prefix}_D${bname_key}_${2}"
      ;;
  esac
}

##
#
##
function bname_retention() {
  local retention="${BNAME_RETENTION:-*/0/0/0}///"

  local retention_day=$(echo "${retention}" | cut -d/ -f1)
  local retention_week=$(echo "${retention}" | cut -d/ -f2)
  local retention_month=$(echo "${retention}" | cut -d/ -f3)
  local retention_year=$(echo "${retention}" | cut -d/ -f4)

  [ -z "${retention_week}" ] && local retention_week=0
  [ -z "${retention_month}" ] && local retention_month=0
  [ -z "${retention_year}" ] && local retention_year=0

  local retention="${retention_day}/${retention_week}/${retention_month}/${retention_year}"

  case $1 in
    day)
      echo "${retention}" | cut -d/ -f1
      ;;
    week)
      echo "${retention}" | cut -d/ -f2
      ;;
    month)
      echo "${retention}" | cut -d/ -f3
      ;;
    year)
      echo "${retention}" | cut -d/ -f4
      ;;
    *)
      echo "${retention}"
      ;;
  esac
}

##
#
##
function bname_char_mask() {
  local file=$1
  for position in $2; do
    # shellcheck disable=SC2001
    file=$(echo "${file}" | sed "s/./^/${position}")
  done
  echo "${file}"
}

##
#
##
function bname_mask() {
  case "$1" in
    build:day)
      # shellcheck disable=SC2001
      bname_char_mask "$2" "9 10 11 12 19"
      ;;
    build:week)
      # shellcheck disable=SC2001
      bname_char_mask "$2" "5 6 7 8 9 10 12 13 14 15 16 17 18 19 20 21 22 23"
      ;;
    build:month)
      # shellcheck disable=SC2001
      bname_char_mask "$2" "5 6 7 8 9 10 12 13 14 15 16 17 18 19 20 21 22 23"
      ;;
    build:year)
      # shellcheck disable=SC2001
      bname_char_mask "$2" "5 6 7 8 9 10 12 13 14 15 16 17 18 19 20 21 22 23"
      ;;
    clean:day)
      # shellcheck disable=SC2001
      bname_char_mask "$2" "3 4 5 6 7 8 9 10 12 13 14 15 16 17 18 19 20 21"
      ;;
    clean:week)
      # shellcheck disable=SC2001
      bname_char_mask "$2" "3 4 5 6 7 8 9 10 12 13 14 15 16 17 18 19 20 21"
      ;;
    clean:month)
      # shellcheck disable=SC2001
      bname_char_mask "$2" "3 4 5 6 7 8 9 10 12 13 14 15 16 17 18 19 20 21"
      ;;
    clean:year)
      # shellcheck disable=SC2001
      bname_char_mask "$2" "3 4 5 6 7 8 9 10 12 13 14 15 16 17 18 19 20 21"
      ;;
  esac
}

##
# Build
##
function bname_build() {
  bname_stage=$1
  bname_build=yes
  bname_snapshot=$(bname_snapshot "${bname_stage}" "${bname_file}")
  bname_a=$(bname_mask "build:${bname_stage}" "$bname_snapshot")
  for file in $bname_bucket; do
    bname_b=$(bname_mask "build:${bname_stage}" "$file")
    echo "# build check: $bname_snapshot ($bname_a) vs $file ($bname_b)"
    [ "${bname_a}" = "${bname_b}" ] && bname_build=no
  done
  if [ "${bname_build}" = "yes" ]; then
    echo "+ $bname_snapshot"
  else
    echo "# ignore '$bname_snapshot'"
  fi
}

##
# Clean
##
function bname_clean() {
  bname_count=0
  bname_clean=no
  bname_stage=$1
  bname_snapshot=$(bname_snapshot "${bname_stage}" "${bname_file}")
  bname_build_a=$(bname_mask "build:${bname_stage}" "$bname_snapshot")
  bname_clean_a=$(bname_mask "clean:${bname_stage}" "$bname_snapshot")
  for file in $bname_bucket; do
    bname_build_b=$(bname_mask "build:${bname_stage}" "$file")
    bname_clean_b=$(bname_mask "clean:${bname_stage}" "$file")
    #echo "# build check: $bname_snapshot ($bname_build_a) vs $file ($bname_build_b)"
    #echo "# clean check: $bname_snapshot ($bname_clean_a) vs $file ($bname_clean_b)"
    if [ "${bname_clean_a}" = "${bname_clean_b}" ]; then
      if [ "${bname_build_a}" = "${bname_build_b}" ]; then
        bname_clean=yes
      fi
      if [ "${bname_clean}" = "yes" ]; then
        bname_count=$((++bname_count))
      fi
      if [ "${bname_count}" -gt "1" ]; then
        echo "- ${file}"
      fi
    fi
  done
}

##
#
##
function main() {
  bname_file=$1
  bname_bucket=$(while read -r line; do echo "${line}"; done | sort -r | xargs)
  bname_stages="day week month year"
  local bname_date=$(bname_date)
  echo "# date: ${bname_date}"
  for stage in $bname_stages; do
    local retention=$(bname_retention "${stage}")
    echo "# ${stage}=${retention}"
    if [ "${retention}" = "*" ] || [ "${retention}" -gt "0" ]; then
      bname_build "$stage"
    fi
    if [ "${retention}" != "*" ] && [ "${retention}" -gt "0" ]; then
      bname_clean "$stage"
    fi
  done
}

##
#
##
if [ -n "${was_sourced}" ]; then
  export -f bname_retention
else
  main "${@}"
fi
